### ISSUE TITLE
Latest update - type 'bool' is not a subtype of type 'LyricsAlignment' in type cast

### ISSUE THREAD

**Issue by DomiStyle** [flathub/com.unicornsonlsd.finamp#4]
Cool to see that Finamp is now available for desktop, I get the following exception when starting the latest version:

```
[Startup/INFO] 2024-06-18 09:44:18.063372: App starting, logging initialized.
[ErrorApp/SEVERE] 2024-06-18 09:44:18.072938: type 'bool' is not a subtype of type 'LyricsAlignment' in type cast
		#0      FinampSettingsAdapter.read (package:finamp/models/finamp_models.g.dart:173)
		#1      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:328)
		#2      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:276)
		#3      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21)
		#4      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42)
		<asynchronous suspension>
		#5      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86)
		<asynchronous suspension>
		#6      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
		<asynchronous suspension>
		#7      HiveImpl.openBox (package:hive/src/hive_impl.dart:142)
		<asynchronous suspension>
		#8      Future.wait.<anonymous closure> (dart:async/future.dart:524)
		<asynchronous suspension>
		#9      setupHive (package:finamp/main.dart:221)
		<asynchronous suspension>
		#10     main (package:finamp/main.dart:80)
		<asynchronous suspension>
```

Downgrading solves this for now: `sudo flatpak update --commit eaf2a060786b54a956d8f3abbf40e8ad91993db32b12d627a69a7e8d81006150  com.unicornsonlsd.finamp`

**Comment by baarkerlounger** [comment]
Can you check if deleting your data dir resolves this? (`~/.var/app/com.unicornsonlsd.finamp`). It'll be recreated when you next start the app.

**Comment by DomiStyle** [comment]
Yes, that seems to work. Thanks!
